### ISSUE TITLE
Add SQL module

### ISSUE THREAD

**Issue by yoavxyoav** [yoavxyoav/billboard-insights#12]

**Comment by yoavxyoav** [comment]
Ideally, the SQL class could work in two possible ways:
It could iterate over a list of Charts (i.e, something that returns from get_time_range() ) and insert each chart to the database, or
an instance of the class would be passed to the scraper upon instantiation (this would be optional), and will insert the scrapped weeks as they come streaming from get_time_range()

**Comment by ybond** [comment]
done
